name: Deploy WordPress

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Compress the application
    - name: Compress application
      run: |
        mkdir temp_archive
        cp -r $(ls -A | grep -vE '^temp_archive$') temp_archive/
        tar -czf app_$(date +'%Y-%m-%d').tar.gz -C temp_archive .
        rm -rf temp_archive

    # Step 3: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 4: Upload the application to the S3 public bucket
    - name: Upload application to S3 (Public Bucket)
      run: |
        aws s3 cp app_$(date +'%Y-%m-%d').tar.gz s3://${{ secrets.S3_BUCKET_PUBLIC }}/

    # Step 5: Refresh the Auto Scaling Group
    - name: Refresh Auto Scaling Group
      run: |
        REFRESH_STATUS=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name ${{ secrets.ASG_NAME }} | jq -r '.InstanceRefreshes[0].Status // "None"')
        if [ "$REFRESH_STATUS" == "InProgress" ]; then
          echo "An Instance Refresh is already in progress. Exiting."
          exit 0
        fi
        aws autoscaling start-instance-refresh --auto-scaling-group-name ${{ secrets.ASG_NAME }}

    # Step 6: Clean old builds from the S3 public bucket
    - name: Clean old builds from S3
      run: |
        aws s3 ls s3://${{ secrets.S3_BUCKET_PUBLIC }}/ | awk '{print $4}' | while read file; do
          if [[ $file == app_*.tar.gz ]]; then
            build_date=$(echo $file | sed 's/app_\([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\).tar.gz/\1/')
            build_timestamp=$(date -d $build_date +%s)
            current_timestamp=$(date +%s)
            diff=$(( (current_timestamp - build_timestamp) / 86400 ))
            if [[ $diff -gt 7 ]]; then
              aws s3 rm s3://${{ secrets.S3_BUCKET_PUBLIC }}/$file
            fi
          fi
        done
