name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Package the repository
      - name: Package application
        run: |
          mkdir -p /tmp/app_package
          cp -R . /tmp/app_package
          tar --exclude='/tmp/app_package/.git' -czf app_$(date +%Y%m%d).tar.gz -C /tmp/app_package .

      # 3. Upload to S3
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp app_$(date +%Y%m%d).tar.gz s3://omar-app-bucket/

      # 4. Setup Apache on EC2
      - name: Setup Apache on EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/tet.pem
          chmod 400 /tmp/tet.pem
          ssh -i /tmp/tet.pem -o StrictHostKeyChecking=no ec2-user@3.94.131.73 \
          "sudo yum install httpd -y && sudo systemctl enable httpd && sudo systemctl start httpd && sudo mkdir -p /var/www/html && sudo chown ec2-user:ec2-user /var/www/html"

      # 5. Deploy to EC2
      - name: Deploy to EC2
        run: |
          scp -i /tmp/tet.pem -o StrictHostKeyChecking=no app_$(date +%Y%m%d).tar.gz ec2-user@3.94.131.73:/tmp/
          ssh -i /tmp/tet.pem -o StrictHostKeyChecking=no ec2-user@3.94.131.73 \
          "sudo tar -xzf /tmp/app_$(date +%Y%m%d).tar.gz -C /var/www/html && sudo systemctl restart httpd"

      # 6. Cleanup old builds
      - name: Cleanup old builds
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 ls s3://omar-app-bucket/ | awk '{print $4}' | while read file; do
            creation_date=$(aws s3api head-object --bucket omar-app-bucket --key $file --query "LastModified" --output text)
            if [[ $(date -d "$creation_date" +%s) -lt $(date -d "7 days ago" +%s) ]]; then
              aws s3 rm s3://omar-app-bucket/$file
            fi
          done
